version: '2'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
     - ./templates:/etc/nginx/templates
     - ./etc/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
        - ./db-data:/var/lib/postgresql/data/pgdata
  odoo13:
    image: odoo:13
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./odoo-data:/var/lib/odoo
    restart: always
